package br.com.marketlist.api.model;

import java.time.OffsetDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import br.com.marketlist.api.converters.OffsetDateTimeConverter;
import lombok.Data;


@Data
@DynamoDBTable(tableName = "category")
public class Category {
	
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
	private OffsetDateTime dateCreated;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
	private OffsetDateTime dateUpdated;
	@DynamoDBAttribute
	private UserApp updatedFor;
	
	
	
}
