package br.com.marketlist.api.model;

import java.io.Serializable;
import java.util.Optional;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName = "items")
public class Item extends AbstractModel implements Serializable{

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5262854310996863136L;
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@Getter @Setter
	private String id;
	
	
	@DynamoDBAttribute
	@DynamoDBTyped(DynamoDBAttributeType.M)
	@Getter @Setter
	private Optional<Category> category;

	
}
