package br.com.marketlist.api.model;

import java.time.OffsetDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fasterxml.jackson.annotation.JsonIgnore;

import br.com.marketlist.api.converters.OffsetDateTimeConverter;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "userApp")
public class UserApp{
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	@JsonIgnore(value = true)
	private String password;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
	private OffsetDateTime dateCreated;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
	private OffsetDateTime dateUpdated;
	
	
	
}
